[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Geist"
url = "static/Geist-VariableFont_wght.ttf"
style = "normal"

[[theme.fontFaces]]
family = "GeistMono"
url = "app/static/GeistMono-VariableFont_wght.ttf"
style = "normal"

[theme]
font = "Geist"
codeFont = "GeistMono"
baseRadius = "0.5rem"

[theme.sidebar]
baseRadius = "small"

